version: 2
jobs:
  build:
    docker: 
      image: cibuilds/hugo:latest
    working_directory: ~/hugo
    environment:
      HUGO_BUILD_DIR: ~/hugo/public
    steps:
      - run: apk add update && apk add git
      - checkout
      - run: git submodule sync && git submodule update
      - run: apk add --update python python-dev py-pip build-base
      - run: pip instal awscli 
      - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
      - run: |
          htmlproofer $HUGO_BUILD_DIR 
workflows:
  jobs:
    - build          
