version: 2.1
jobs:
  build:
    docker: 
      - image: advaitkukade/html:v2.0 
    steps:
      - run: apk add nginx 
      - checkout
    #  - run: git submodule sync && git submodule update
    #  - run: apk add --update python python-dev py-pip build-base
    #  - run: pip instal awscli 
    #  - run: HUGO_ENV=production hugo -v -d $HUGO_BUILD_DIR
    #  - run: |
    #      htmlproofer $HUGO_BUILD_DIR 
workflows:
  workflow_1:
    jobs:
      - build   
